// Code generated by Kitex v0.7.0. DO NOT EDIT.

package userservice

import (
			"context"
				user "douyin/kitex_gen/user"
				client "github.com/cloudwego/kitex/client"
				kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
 }

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Register":
			kitex.NewMethodInfo(registerHandler, newUserServiceRegisterArgs, newUserServiceRegisterResult, false),
		"Login":
			kitex.NewMethodInfo(loginHandler, newUserServiceLoginArgs, newUserServiceLoginResult, false),
		"GetUserInfoById":
			kitex.NewMethodInfo(getUserInfoByIdHandler, newUserServiceGetUserInfoByIdArgs, newUserServiceGetUserInfoByIdResult, false),
		"GetUserInfoByName":
			kitex.NewMethodInfo(getUserInfoByNameHandler, newUserServiceGetUserInfoByNameArgs, newUserServiceGetUserInfoByNameResult, false),
		"CheckUserExists":
			kitex.NewMethodInfo(checkUserExistsHandler, newUserServiceCheckUserExistsArgs, newUserServiceCheckUserExistsResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":	 "user",
		"ServiceFilePath": "idl\\user.thrift",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName: 	 serviceName,
		HandlerType: 	 handlerType,
		Methods:     	 methods,
		PayloadCodec:  	 kitex.Thrift,
		KiteXGenVersion: "v0.7.0",
		Extra:           extra,
	}
	return svcInfo
}



func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}


func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}


func getUserInfoByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*user.UserServiceGetUserInfoByIdArgs)
	realResult := result.(*user.UserServiceGetUserInfoByIdResult)
	success, err := handler.(user.UserService).GetUserInfoById(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newUserServiceGetUserInfoByIdArgs() interface{} {
	return user.NewUserServiceGetUserInfoByIdArgs()
}

func newUserServiceGetUserInfoByIdResult() interface{} {
	return user.NewUserServiceGetUserInfoByIdResult()
}


func getUserInfoByNameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*user.UserServiceGetUserInfoByNameArgs)
	realResult := result.(*user.UserServiceGetUserInfoByNameResult)
	success, err := handler.(user.UserService).GetUserInfoByName(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newUserServiceGetUserInfoByNameArgs() interface{} {
	return user.NewUserServiceGetUserInfoByNameArgs()
}

func newUserServiceGetUserInfoByNameResult() interface{} {
	return user.NewUserServiceGetUserInfoByNameResult()
}


func checkUserExistsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*user.UserServiceCheckUserExistsArgs)
	realResult := result.(*user.UserServiceCheckUserExistsResult)
	success, err := handler.(user.UserService).CheckUserExists(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newUserServiceCheckUserExistsArgs() interface{} {
	return user.NewUserServiceCheckUserExistsArgs()
}

func newUserServiceCheckUserExistsResult() interface{} {
	return user.NewUserServiceCheckUserExistsResult()
}


type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}


func (p *kClient) Register(ctx context.Context , request *user.UserRegisterRequest) (r *user.UserRegisterResponse, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Request = request
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context , request *user.UserLoginRequest) (r *user.UserLoginResponse, err error) {
	var _args user.UserServiceLoginArgs
	_args.Request = request
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfoById(ctx context.Context , request *user.UserInfoByIdRequest) (r *user.UserInfoByIdResponse, err error) {
	var _args user.UserServiceGetUserInfoByIdArgs
	_args.Request = request
	var _result user.UserServiceGetUserInfoByIdResult
	if err = p.c.Call(ctx, "GetUserInfoById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfoByName(ctx context.Context , request *user.UserInfoByNameRequest) (r *user.UserInfoByNameResponse, err error) {
	var _args user.UserServiceGetUserInfoByNameArgs
	_args.Request = request
	var _result user.UserServiceGetUserInfoByNameResult
	if err = p.c.Call(ctx, "GetUserInfoByName", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckUserExists(ctx context.Context , request *user.UserExistsRequest) (r *user.UserExistsResponse, err error) {
	var _args user.UserServiceCheckUserExistsArgs
	_args.Request = request
	var _result user.UserServiceCheckUserExistsResult
	if err = p.c.Call(ctx, "CheckUserExists", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

