// Code generated by Kitex v0.6.2. DO NOT EDIT.

package commentservice

import (
	"context"
	comment "douyin/kitex_gen/comment"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentAction(ctx context.Context, request *comment.CommentActionRequest, callOptions ...callopt.Option) (r *comment.CommentActionResponse, err error)
	GetCommentList(ctx context.Context, request *comment.CommentListRequest, callOptions ...callopt.Option) (r *comment.CommentListResponse, err error)
	GetCommentCount(ctx context.Context, videoId int32, callOptions ...callopt.Option) (r int32, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CommentAction(ctx context.Context, request *comment.CommentActionRequest, callOptions ...callopt.Option) (r *comment.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, request)
}

func (p *kCommentServiceClient) GetCommentList(ctx context.Context, request *comment.CommentListRequest, callOptions ...callopt.Option) (r *comment.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, request)
}

func (p *kCommentServiceClient) GetCommentCount(ctx context.Context, videoId int32, callOptions ...callopt.Option) (r int32, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentCount(ctx, videoId)
}
