package constant

const EtcdAddr = "127.0.0.1:2379"
const ApiServiceName = "api-service"
const ApiServicePort = ":8080"
const CommentServiceName = "comment-service"
const CommentServicePort = ":4001"
const UserServiceName = "user-service"
const UserServicePort = ":4002"
const VideoServiceName = "video-service"
const VideoServicePort = ":4003"
const RelationServiceName = "relation-service"
const RelationServicePort = ":4004"
const MessageServiceName = "message-service"
const MessageServicePort = ":4005"
const FavoriteServiceName = "favorite-service"
const FavoriteServicePort = ":4006"
